### ISSUE TITLE
Kernel source sync

### ISSUE THREAD

**Issue by inferno0230** [OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm7550#3]
@OnePlusOSSAdmin 

Please release the kernel repo needed for Nord Ce 4, only kernel_modules repo was released in previous sync and main kernel repo (android_kernel_oneplus_sm7550) is missing.

Thanks

**Comment by OnePlusOSSAdmin** [comment]
It's OK now.
https://github.com/OnePlusOSS/android_kernel_oneplus_sm7550
